name: breathebox
description: A guided breathing app with Riverpod state management, animations, audio cues, and persistent settings.
publish_to: 'none' # Remove if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🧠 State management
  flutter_riverpod: ^2.5.1

  # 💾 Local persistence
  shared_preferences: ^2.5.3

  # 🎨 Fonts (optional UI polish)
  google_fonts: ^6.2.1

  # 🔊 Audio playback
  audioplayers: ^6.5.0

  # 📱 iOS/Android icons & platform style
  cupertino_icons: ^1.0.8

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # 🎵 Breathing phase cues
    - assets/sounds/inhale.mp3
    - assets/sounds/hold.mp3
    - assets/sounds/exhale.mp3
    - assets/sounds/rest.mp3

    # Optionally add ambient loop or other sounds here
    # - assets/sounds/ambient.mp3
